# This is a basic workflow to help you get started with Actions

name: Build and Deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main, cicd2]
    # paths:
    #   - "src/**"

env:
  JAVA_VERSION: "1.8"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@master
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: ${{ env.JAVA_VERSION }}
      - name: Build with Maven
        run: mvn package --file pom.xml
      - name: Rename WAR
        run: mv target/*.war silp-todomate.war
      - name: Create Private Key File
        run: 'echo "$SSH_KEY" > key'
        shell: bash
        env:
          SSH_KEY: ${{secrets.KEY}}
      - name: Upload WAR to remote Server
        run: "scp -i key silp-todomate.war ${{ secrets.USERNAME }}@todomate.handong.us:/opt/tomcat/webapps/silp-todomate.war"

      # - name: Login to Heroku
      #   uses: akhileshns/heroku-deploy@v3.12.12
      #   with:
      #     heroku_api_key: ${{secrets.HEROKU_API_KEY}}
      #     heroku_app_name: "todomate"
      #     heroku_email: "22000462@handong.edu"
      #     justlogin: true
      # - name: Install Java Plugin
      #   run: heroku plugins:install java
      # - name: Deploy WAR
      #   run: heroku war:deploy target/*.war --app todomate
